spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 500 # 컬렉션 조회 페이징 및 최적화
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #        use_sql_comments: true
    open-in-view: false

  datasource:
    app:
      driver-class-name: org.postgresql.Driver
      url: ENC(nbd69nrSqB/XNsap0X4BBho5QZ6g5mIOtuT1JZpqgjBAT6rUQ/524zsNqui7r4sY+2pBSGdAgiLsJwdYRW+TBdMDFXfuYqkzsMZ2fl7Nh8fdZWMc/bd5ThOHtQAHOF2u)
      username: ENC(iC7mB1dsNTspESgshgJoIfZxypFH10nD)
      password: ENC(OJ1FF9s7fV9tw8nZ1LrH3e4UXUiWXJzl)
    log:
      driver-class-name: org.postgresql.Driver
      url: ENC(nbd69nrSqB/XNsap0X4BBho5QZ6g5mIOtuT1JZpqgjBAT6rUQ/524zsNqui7r4sY+2pBSGdAgiLsJwdYRW+TBdMDFXfuYqkzsMZ2fl7Nh8fdZWMc/bd5ThOHtQAHOF2u)
      username: ENC(iC7mB1dsNTspESgshgJoIfZxypFH10nD)
      password: ENC(OJ1FF9s7fV9tw8nZ1LrH3e4UXUiWXJzl)

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

# DB 데이터 암호화 용도 => 이값 변경해야함
aes:
  secret-key: ENC(fTa2qwMWVDf6dh0nqBhfE6tGobUjdmvFk0DQux6Ap1xnZW2Ym0R7NCgc2oqU26y0)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )
